version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0 # .NET SDK 8.x image
    steps:
      - checkout
      - run:
          name: Restore NuGet Packages
          command: dotnet restore **/WebAppNEE.csproj
      - run:
          name: Build Solution
          command: dotnet build **/WebAppNEE.csproj --configuration Release
      - run:
          name: Publish Application
          command: dotnet publish **/WebAppNEE.csproj --configuration Release --output publish
      - persist_to_workspace:
          root: publish
          paths:
            - .

workflows:
  version: 2
  build:
    jobs:
      - build
