version: 2.1

executors:
  dotnet-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0 # Use .NET SDK 8.x Docker image

jobs:
  build:
    executor: dotnet-executor
    steps:
      - checkout
      - run:
          name: Restore NuGet Packages
          command: dotnet restore "WebAppNEE.sln"
      - run:
          name: Publish Symbols
          command: |
            find . -type f -name "*.pdb" -exec cp {} build/symbols/ \; || true
      - run:
          name: Publish WebAppNEE
          command: |
            dotnet publish WebAppNEE/WebAppNEE.csproj \
              --configuration Release \
              --output build/artifacts/WebAppNEE
      - run:
          name: Publish InstallationAPI
          command: |
            dotnet publish InstallationAPI/InstallationAPI.csproj \
              --configuration Release \
              --output build/artifacts/InstallationAPI
      - run:
          name: Publish AddMap
          command: |
            dotnet publish AddMap/addMap.csproj \
              --configuration Release \
              --output build/artifacts/AddMap
      - run:
          name: Copy Files
          command: |
            mkdir -p build/copy
            cp -r **/bin/Release/* build/copy/
      - run:
          name: Build Solution
          command: |
            dotnet build "WebAppNEE.sln" \
              --configuration Release
      - store_artifacts:
          path: build/artifacts
          destination: drop

deploy:
    executor: dotnet-executor
    steps:
      - checkout
      - run:
          name: Configure Git
          command: |
            git config --global user.email "circleci@yourdomain.com"
            git config --global user.name "CircleCI Deployment"
      - run:
          name: Deploy WebAppNEE via Git
          command: |
            cd build/artifacts/WebAppNEE
            git init
            git remote add azure https://nerdetails.scm.azurewebsites.net:443/nerdetails.git
            git add .
            git commit -m "Deploy WebAppNEE"
            git push azure master --force
          environment:
            GIT_HTTP_USER: $AZURE_GIT_USERNAME
            GIT_HTTP_PASSWORD: $AZURE_GIT_PASSWORD
      - run:
          name: Deploy InstallationAPI via Git
          command: |
            cd build/artifacts/InstallationAPI
            git init
            git remote add azure https://installationapi2024.scm.azurewebsites.net:443/InstallationAPI2024.git
            git add .
            git commit -m "Deploy InstallationAPI"
            git push azure master --force
          environment:
            GIT_HTTP_USER: $AZURE_GIT_USERNAME
            GIT_HTTP_PASSWORD: $AZURE_GIT_PASSWORD
      - run:
          name: Deploy AddMap via Git
          command: |
            cd build/artifacts/AddMap
            git init
            git remote add azure https://addmap.scm.azurewebsites.net:443/addmap.git
            git add .
            git commit -m "Deploy AddMap"
            git push azure master --force
          environment:
            GIT_HTTP_USER: $AZURE_GIT_USERNAME
            GIT_HTTP_PASSWORD: $AZURE_GIT_PASSWORD

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
